apiVersion: apps/v1
kind: Deployment
metadata:
  name: annms-db-admin-{{ .Values.env }}
  namespace: annms-{{ .Values.env }}
  labels:
    app: annms-db-admin-{{ .Values.env }}
spec:
  replicas: {{ .Values.dbAdmin.replicas }}
  selector:
    matchLabels:
      app: annms-db-admin-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: annms-db-admin-{{ .Values.env }}
    spec:
      containers:
      - name: annms-db-admin-{{ .Values.env }}
        image: {{ .Values.dbAdmin.image }}
        {{- if .Values.dbAdmin.envValues }}
        env:
        {{- range $key, $value := .Values.dbAdmin.envValues }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: annms-db-admin-{{ .Values.env }}-svc
  namespace: annms-{{ .Values.env }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3307
    targetPort: 80
  selector:
    app: annms-db-admin-{{ .Values.env }}