apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: annms-ingress-{{ .Values.env }}
  namespace: annms-{{ .Values.env }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/rewrites:"serviceName=annms-app-prod-svc rewrite=/"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^\/(phpmyadmin|phpmyadmindev)$ $1/ permanent; 

spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: letsencrypt
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.adonisApp.path }}
        pathType: Prefix
        backend:
          service:
            name: annms-app-{{ .Values.env }}-svc
            port:
              number: 3333
      - path: {{ .Values.ingress.dbAdmin.path }}
        pathType: Prefix
        backend:
          service:
            name: annms-db-admin-{{ .Values.env }}-svc
            port:
              number: 3307
