apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: annms-app-ingress-{{ .Values.env }}
  namespace: annms-{{ .Values.env }}
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: letsencrypt
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.adonisApp.path }}
        pathType: Prefix
        backend:
          service:
            name: annms-app-{{ .Values.env }}-svc
            port:
              number: 3333