apiVersion: apps/v1
kind: Deployment
metadata:
  name: annms-app-{{ .Values.env }}
  namespace: annms-{{ .Values.env }}
  labels:
    app: annms-app-{{ .Values.env }}
spec:
  replicas: {{ .Values.adonisApp.replicas }}
  selector:
    matchLabels:
      app: annms-app-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: annms-app-{{ .Values.env }}
    spec:
      containers:
      - name: annms-app-{{ .Values.env }}
        image: {{ .Values.adonisApp.image }}
        {{- if .Values.adonisApp.envValues }}
        env:
        {{- range $key, $value := .Values.adonisApp.envValues }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: annms-app-{{ .Values.env }}-svc
  namespace: annms-{{ .Values.env }}
spec:
  type: ClusterIP
  ports:
  - port: 3333
  selector:
    app: annms-app-{{ .Values.env }}