apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: annms-ingress
  namespace: annms-workload
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/rewrites: "serviceName=annms-app-svc rewrite=/"
    nginx.org/rewrites: "serviceName=annms-db-admin-svc rewrite=/"

spec:
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: annms-app-svc
                port: 
                  number: 3333

          - path: /annms-db-admin
            pathType: Prefix
            backend:
              service:
                name: annms-db-admin-svc
                port: 
                  number: 3307
  tls:
    - hosts:
      - annoucementsystem.ddns.net