apiVersion: apps/v1
kind: Deployment
metadata:
  name: annms-dbms
  namespace: annms-workload
  labels:
    app: annms-dbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annms-dbms
  template:
    metadata:
      labels:
        app: annms-dbms
    spec:
      containers:
      - name: annms-dbms
        image: ghcr.io/integrated-int317-int365-announcement/database:dev
        {{- if .Values.dbEnv }}
        env:
        {{- range $key, $value := .Values.dbEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: annms-dbms-svc
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: annms-dbms
