apiVersion: v1
description: Announcement System workload Helm Chart
name: announcement-system-workload
version: 1.0.0
appVersion: 1.0.0
sources:
  - https://github.com/integrated-int317-int365-announcement/adonis-announcement-project
